// This assembly is included in the following assemblies:
//
// nav.adoc

[id='assembly-knative-v050-ocp-4x']
= Knative v0.5.0 on an OpenShift 4.x cluster
include::_attributes.adoc[]


// Knative on OpenShift 4.x cluster overview
//include::con_knative-v050-OCP-4x.adoc[leveloffset=+1]

// Installing Knative on an OpenShift cluster 4.x using the script provided
//include::proc_knative-v050-install-OCP-4x.adoc[leveloffset=+1] 

// Allowing external access to Knative services for OCP 4.x (Creating an OpenShift Route pointing to the istio-ingressgateway for each of your Knative Service)
//include::proc_knative-v050-creating-OCP-route-pointing-istio.adoc[leveloffset=+1]


Knative allows for greater consistency and more granular scalability across applications and teams.

The benefits of Knative on OpenShift include:

* Use Kubernetes and OpenShift to build, scale, and manage serverless applications in any cloud, on-premise, or in a hybrid environment.

* Build modern, serverless functions, and support legacy apps through event sources. You can manage them alongside your other applications on Red Hat OpenShift.

* Knative allows app teams to focus on building products. Knative installs on OpenShift using Operators, simplifying installation and automating updates and management.