//
//

= Knative on OpenShift Container Platform

Red Hat OpenShift Serverless is based on the open source Knative project. When Knative is integrated with Red Hat OpenShift, it provides solutions for common challenges faced by developers.

Red Hat OpenShift Serverless simplifies the process of getting code from development into production, by reducing the requirement for developer input in infrastructure set up or back-end development, allowing developers to spend more time writing code.

*The components of Knative are:*

* *Serving*: Deploy and scale functions and serverless applications. Knative Serving can be installed on OpenShift Container Platform using the OpenShift Serverless Operator.
* *Eventing*: Consume and produce events to bind event sources to services. Knative Eventing can be installed on OpenShift Container Platform using the Knative Eventing Operator.

== Resources
* link:https://redhat-developer-demos.github.io/knative-tutorial[Knative Tutorial]
* link:https://docs.openshift.com/container-platform/4.1/serverless/installing-openshift-serverless.html#installing-serverless-operator_installing-openshift-serverless[OpenShift Serverless Operator documentation]
