= Overview

[IMPORTANT]
====
{serverlessproductname} - Technology and Developer Preview releases contain features and functionalities that might not be fully tested. Customers are encouraged to provide feedback on Technology and Developer Preview releases.

Technology and Developer Preview releases are not production-ready, and customers are recommended to avoid using the project for production or business-critical workloads.

{serverlessproductname} provides information about additional, advanced use cases and integrations that are possible using OpenShift Container Platform and OpenShift Serverless, but are for technology and development purposes and are not officially supported by Red Hat.

For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview

If you need assistance with {serverlessproductname} - Technology and Developer Preview releases, please reach out on the serverless-interest@redhat.com mailing list, where the Red Hat Development Team will be happy to assist you based on the availability and work schedules.
====

Before you can complete the tasks documented on this site, you will need a working installation of {serverlessproductname}.

* See link:https://access.redhat.com/articles/4912821[OpenShift Serverless supported configurations]
* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/serverless/install[Installing OpenShift Serverless] documentation
