= Overview

[IMPORTANT]
====
OpenShift Serverless - Developer Preview releases contain features and functionalities that might not be fully tested. Customers are encouraged to provide feedback on Developer Preview releases.

Developer Preview releases are not production-ready, and customers are recommended to avoid using the project for production or business-critical workloads. 

If you need assistance with OpenShift Serverless - Developer Preview releases, please reach out on the following mailing list, where the Red Hat Development Team will be happy to assist you based on the availability and work schedules: serverless-interest@redhat.com
====

_OpenShift Serverless_ provides information about additional, advanced use cases and integrations that are possible using OpenShift Container Platform and OpenShift Serverless, but are for development purposes only and are not officially supported by Red Hat.

Before you can complete the tasks documented on this site, you will need a working installation of OpenShift Serverless.

* See link:https://access.redhat.com/articles/4912821[OpenShift Serverless supported configurations]
* See link:https://docs.openshift.com/container-platform/4.8/serverless/admin_guide/install-serverless-operator.html[Installing OpenShift Serverless] documentation
