//
//

= Knative on Red Hat OpenShift Container Platform

When Knative is integrated with Red Hat OpenShift Container Platform, it provides solutions for common challenges faced by developers by simplifying the process of getting code from development into production.

*Knative Components:*

* *Knative Serving*: Deploy and scale functions and serverless applications. Knative Serving can be installed on OpenShift Container Platform using the OpenShift Serverless Operator.
* *Knative Eventing*: Consume and produce events to bind event sources to services. Knative Eventing can be installed on OpenShift Container Platform using the Knative Eventing Operator.

== Operators on Red Hat OpenShift Container Platform

Operators offer a method of packaging, deploying, and managing a Red Hat OpenShift Container Platform application.

As a cluster administrator, you can link:https://openshift-knative.github.io/docs/docs/proc_knative-eventing.html[install the Knative Eventing Operator] from the OperatorHub using the Red Hat OpenShift Container Platform web console. You can then subscribe the Operator to one or more namespaces to make it available on your cluster.

== Resources
* link:https://redhat-developer-demos.github.io/knative-tutorial[Knative Tutorial]
* For more information about using Operators on Red Hat OpenShift Container Platform, see the link:https://docs.openshift.com/container-platform/4.2/operators/olm-what-operators-are.html[Red Hat OpenShift Container Platform Operators documentation].
* link:https://github.com/openshift-knative/docs[GitHub repository]
