= Knative Integration Source
:compat-mode!:
// Metadata:
:description: Knative Integration Source in {serverlessproductname}

This page describes how to use the new `IntegrationSource` API for Eventing in {serverlessproductname}. The `IntegrationSource` is a Knative Eventing custom resource supporting selected https://camel.apache.org/camel-k/latest/kamelets/kamelets.html[Kamelets] from the https://camel.apache.org/[Apache Camel] project. Kamelets allow users to connect to 3rd party system for improved connectivity, they can act as "sources" or as "sinks". Therefore the `IntegrationSource` allows to consume data from external systems and forward them into Knative Eventing.

[IMPORTANT]
====
{serverlessproductname} `IntegrationSource` is a Developer Preview feature only.

Developer Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete.
Red Hat does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Developer Preview features, see https://access.redhat.com/support/offerings/devpreview/.
====

== Supported Kamelet sources

* xref:./aws_ddbstreams.adoc[AWS DDB Streams]
* xref:./aws_s3.adoc[AWS S3]
* xref:./aws_sqs.adoc[AWS SQS]
* xref:./timer.adoc[Generic timer]
