// [id="about-functions"]
= About OpenShift Serverless Functions

{product-name} enables developers to create and deploy stateless, event-driven functions as a Knative service on OpenShift Container Platform.

The {short-name} `func` CLI is provided as a plugin for the Knative `kn` CLI.
{product-name} uses the link:https://buildpacks.io/[CNCF Buildpack API] to create container images.
Once a container image has been created, the CLI can deploy the container image as a Knative service on the cluster.
//  configured in ``~/.kube/config`.
// Admin guide, configure kubeconfig? Point to OCP docs? Is there additional config needed for serverless besides CLI connecting kn to cluster?
//TODO add CLI connecting to cluster docs to OCP docs?

// [id="about-functions-runtimes"]
.Runtimes

{product-name} provides templates that can be used to create basic functions for the following runtimes:

* link:https://golang.org/[Go]
* xref:../functions/dev_guide/nodejs/develop-nodejs.adoc#develop-nodejs[Node.js]
* link:https://quarkus.io/[Quarkus]

// [id="about-functions-triggers"]
.Triggers

{product-name} can be invoked by using a plain http request or a  link:https://cloudevents.io/[CloudEvent] as a trigger.
// TODO: Add architecture section, diagrams, show integration with Knative

// [id="about-functions-additional-resources"]
// == Additional resources
