// This file is an assembly
[id="functions-cli"]
= CLI options

After `kn` is installed, you can enter `kn func` to see available options and commands for using the CLI to create and manage functions.

include::user_guide/kn-func-list-all-commands.adoc[leveloffset=+1]

toc::[]

[id="functions-cli-flags"]
== Flags
// add note for each about which `kn function` commands these apply to.

`path`:: Specifies the location where the function will be created.
** If the path is not specified, the current directory is used.
** If the path does not exist but is specified, it will be created.
+
[NOTE]
====
The function name is the name of the leaf directory at path.
====

`runtime`:: The function runtime language or framework, specified by `-l`.
The default runtime is `go`.
Available runtimes: `node`, `quarkus` and `go`.

`trigger`:: Use the `--trigger` or `-t` flag to specify the function invocation context, or _trigger_.
By default, the trigger is `http`. To create a function for CloudEvents, use
the `events` trigger.
Available triggers: `http` or `events`.

`templates`:: You can specify one or more templates for the function by using the  `--templates` flag.
The default templates location is `/home/<user>/.config/faas/templates`.

// `image`::
