= Deploying your Serverless Workflow application on Kubernetes
:compat-mode!:
// Metadata:
:description: Deploying Serverless Application on Kubernetes
:keywords: kogito, workflow, quarkus, serverless, kn, kubectl, kubernetes
:table-caption: Data Set
// envs for common content
:environment_prereq: Kubernetes Cluster is available
:kubectl_prereq: command-line tool is installed
:cluster_kind: Kubernetes with Knative is ready
:knative_procedure: <<proc-verify-knative-kubernetes, Verifying Knative on Kubernetes>>
:deploy_application: on Kubernetes
:k8s_registry: quay.io
:default_namespace: kiegroup
:registry: target
:container_push: Property to push or not the Container image to the given registry
:quarkus-k8s-plugin: quarkus-kubernetes
:container_push_prop: true
:platform: Kubernetes
:command_line_tool: kubectl
:command_line_tool_name: Kubernetes CLI
// links
:knative_kubernetes_url: https://knative.dev/docs/install/
:verify_knative_url: https://knative.dev/docs/serving/knative-kubernetes-services/#before-you-begin
:quay_io_url: https://quay.io/
:k8s_pull_secret_url: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
:knative_domain_dns_url: https://knative.dev/docs/install/operator/knative-with-operators/#configure-dns
:quarkus_k8s_deploy_url: https://github.com/quarkusio/quarkus/issues/26385


This document describes how to deploy a {product_name} application using a Kubernetes cluster, along with a procedure to run the Knative platform.

// shared pre req
include::../common/_prerequisites.adoc[subs=quotes+]


Before proceeding further, make sure that you have access to the Kubernetes cluster with Knative available.

[[proc-verify-knative-kubernetes]]
== Verifying Knative availability on Kubernetes

To make sure Knative is available, it can be checked with the commands below:

.Verify if Knative is available
[source,shell]
----
kubectl get services -n knative-serving
NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                   AGE
activator-service            ClusterIP   10.97.110.167    <none>        9090/TCP,8008/TCP,80/TCP,81/TCP,443/TCP   44m
autoscaler                   ClusterIP   10.98.64.78      <none>        9090/TCP,8008/TCP,8080/TCP                44m
autoscaler-bucket-00-of-01   ClusterIP   10.111.19.134    <none>        8080/TCP                                  44m
controller                   ClusterIP   10.98.150.141    <none>        9090/TCP,8008/TCP                         44m
default-domain-service       ClusterIP   10.106.202.150   <none>        80/TCP                                    43m
domainmapping-webhook        ClusterIP   10.102.87.208    <none>        9090/TCP,8008/TCP,443/TCP                 44m
net-kourier-controller       ClusterIP   10.100.120.208   <none>        18000/TCP                                 43m
webhook                      ClusterIP   10.108.153.180   <none>        9090/TCP,8008/TCP,443/TCP                 44m
----

For more information on how to figure out if Knative is installed please refer to this link:{verify_knative_url}[link].
If not, follow the installation steps described in the Knative link:{knative_kubernetes_url}[documentation].


[[proc-deploy-sw-application-kubernetes]]
== Deploying your workflow application on Kubernetes

Once Knative is ready, you can initiate the process of deploying your {product_name} application on Kubernetes.


// shared app req
include::../common/_deploy_workflow_application_requisites.adoc[]

[IMPORTANT]
====
By default, Kubernetes does not have any registry installed. You can check with the administrator if a private registry is available. Otherwise, you can publish the Application Container image on the link:{quay_io_url}[Quay.io], or on any other registry of your preference.

If the registry requires authentication you need to create a Pull Secret with the registry credentials, for more information please take a look in this link:{k8s_pull_secret_url}[link].
====

.Procedure
. Create `serverless-workflow-greeting-quarkus` namespace using the following command:
+
include::../common/_create_namespace_and_deploy_info.adoc[]

In the following procedures, you can find different approaches to deploy your workflow application, such as:

* <<proc-deploy-sw-application-knative-cli,Using Knative CLI (kn)>>
* <<proc-deploy-sw-application-kubectl,Using kubectl command-line tool>>
* <<proc-deploy-sw-application-quarkus-cli,Using Quarkus CLI>>


[IMPORTANT]
====
For this tutorial, we use the `default-domain` provided by Knative that configures *Knative Serving* to use
the Magic DNS for naming resolution, for more details please check the Knative link:{knative_domain_dns_url}[documentation].
====

// deploy with kn-cli
include::../common/_proc_deploy_sw_kn_cli.adoc[]

// deploy with kubectl
include::../common/_proc_deploy_sw_kubectl.adoc[]

// deploy with quarkus-cli
include::../common/_proc_deploy_sw_quarkus_cli.adoc[]

include::../../../pages/_common-content/report-issue.adoc[]