= Configuring Workflow Services
:compat-mode!:
// Metadata:
:description: Configuration of Workflow Services deployed by the operator
:keywords: kogito, sonataflow, workflow, serverless, operator, kubernetes, minikube, config, openshift, containers

This document describes how to configure a Workflow service with the {operator_name}.

== Editing the Workflow Configuration

When the operator deploys the Workflow service, it also creates two `ConfigMap`s to store the runtime properties:

* The user properties are defined in a `ConfigMap` named after the `SonataFlow` object with the suffix `-props`. For example, if your Workflow name is `greeting`, then the `ConfigMap` name is `greeting-props`.
* The xref:#managed-props[Managed Properties] are defined in a `ConfigMap` named after the `SonataFlow` object with the suffix `-managed-props`. For example, if your Workflow name is `greeting`, then the `ConfigMap` name is `greeting-managed-props`.

[IMPORTANT]
====
Managed properties always override any user property using the same key name and cannot be edited by the user. Any change would be overwritten by the operator at the next reconciliation cycle.
====

You can use the Kubernetes object editor of your preference to add or edit the link:https://en.wikipedia.org/wiki/.properties[properties] in the Workflow configuration. Using `kubectl` you can do:

.Editing the Workflow Properties
[source,shell,subs="attributes+"]
----
kubectl edit cm <workflow-name>-props
----

Note that it's important to respect the properties format, otherwise the operator will replace your configuration with the default one.

Here's an example of a Workflow properties stored within a ConfigMap:

[#example-of-workflow-config-map]
.Example of a Workflow ConfigMap Properties
[source,yaml,subs="attributes+"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: greeting
  name: greeting-props
  namespace: default
data:
  application.properties: |
    my.properties.key = any-value
----

The underlying runtime engine that executes the Workflow service is based on link:{quarkus_url}[Quarkus]. The `application.properties` key in the ConfigMap means that you can configure the Workflow as you would any link:{quarkus_config_url}[Quarkus application].

Any xref:core/configuration-properties.adoc[{product_name} configuration that the documentation describes] or general Quarkus application property can be configured using this method.

[#managed-props]
== Managed properties

A few properties cannot be changed in this configuration and they are defined in the managed properties file. The table below lists them.

.List of managed properties
[cols="2,1,1"]
|===
|Property Key | Immutable Value | Profile

|quarkus.http.port
|8080
|all

|quarkus.http.host
|0.0.0.0
|all

|org.kie.kogito.addons.knative.eventing.health-enabled
|false
|dev

|===

Other managed properties include:

* The xref:use-cases/advanced-developer-use-cases/service-discovery/kubernetes-service-discovery.adoc[Kubernetes service discovery] properties
* The xref:use-cases/advanced-developer-use-cases/data-index/data-index-quarkus-extension.adoc[Data Index location properties]
* The xref:use-cases/advanced-developer-use-cases/job-service/quarkus-extensions.adoc[Job Service location properties]


If you try to change any of them, the operator will override them with the default, but preserving your changes in other property keys.

== Additional resources

* https://quarkus.io/guides/config-reference#profile-aware-files[Quarkus - Profile aware files]
* xref:core/configuration-properties.adoc[]
* xref:cloud/operator/known-issues.adoc[]
* xref:cloud/operator/developing-workflows.adoc[]
* xref:cloud/operator/build-and-deploy-workflows.adoc[]

include::../../../pages/_common-content/report-issue.adoc[]
