= Install the {operator_name}
:compat-mode!:
// Metadata:
:description: Install the operator on Kubernetes clusters
:keywords: kogito, sonataflow, workflow, serverless, operator, kubernetes, minikube, openshift, containers
// links

:openshift_operator_install_url: https://docs.openshift.com/container-platform/4.13/operators/admin/olm-adding-operators-to-cluster.html
:openshift_operator_uninstall_url: https://docs.openshift.com/container-platform/4.13/operators/admin/olm-deleting-operators-from-cluster.html
:kubernetes_operator_install_url: https://operatorhub.io/how-to-install-an-operator
:kubernetes_operator_uninstall_url: https://olm.operatorframework.io/docs/tasks/uninstall-operator/
:operatorhub_url: https://operatorhub.io/

This guide describes how to install the {operator_name} in a Kubernetes or OpenShift cluster. The operator is in an xref:/cloud/operator/known-issues.adoc[early development stage] (community only) and has been tested on OpenShift 4.11+, Kubernetes 1.22+, and link:{minikube_url}[Minikube].

.Prerequisites
* A Kubernetes or OpenShift cluster with admin privileges. Alternatively, you can use Minikube or KIND.
* `kubectl` command-line tool is installed. Otherwise, Minikube provides it.

== {product_name} Operator OpenShift installation

To install the operator on OpenShift refer to the "link:{openshift_operator_install_url}[Adding Operators to a cluster]" from the OpenShift's documentation.

When searching for the operator in the *Filter by keyword* field, use the word `{operator_openshift_keyword}`. If you're installing from the CLI, the operator's catalog name is `{operator_openshift_catalog}`.

=== Uninstall

To remove the operator on OpenShift refer to the "link:{openshift_operator_uninstall_url}[Deleting Operators from a cluster]" from the OpenShift's documentation.

== {product_name} Operator Kubernetes installation

To install the operator on Kubernetes refer to the  "link:{kubernetes_operator_install_url}[How to install an Operator from OperatorHub.io]" from the OperatorHub's documentation.

When link:{operatorhub_url}[searching for the operator in the *Search OperatorHub* field], use the word `{operator_k8s_keyword}`.

=== Uninstall

To remove the operator on Kubernetes follow the document "link:{kubernetes_operator_uninstall_url}[Uninstall your operator]" from the OLM's documentation.

When searching for the subscription to remove, use the word `{operator_k8s_subscription}`.

== {product_name} Operator Manual Installation

[WARNING]
====
If you're running on Kubernetes or OpenShift, it is highly recommended to install the operator from the OperatorHub or OpenShift Console instead since the installation is managed by OLM. Use this method only if you need a snapshot version or you're running locally on Minikube or KIND.
====

=== Prepare a Minikube instance

[NOTE]
====
You can safely skip this section if you're not using Minikube.
====

.Prerequisites
* A machine with at least 8GB memory and a link:https://en.wikipedia.org/wiki/Multi-core_processor[CPU with 8 cores]
* Docker or Podman installed

Run the following command to create a new instance capable of installing the operator and deploy workflows:

[source,shell,subs="attributes+"]
----
minikube start --cpus 4 --memory 4096 --addons registry --addons metrics-server --insecure-registry "10.0.0.0/24" --insecure-registry "localhost:5000"
----

[NOTE]
====
To speed up the build time, you can increase CPUs and memory options so that your minikube instance will have more resources. For example, use `--cpus 12 --memory 16384`. In order to work, you will have to recreate your instance.
====

If it does not work with the default driver, also known as `docker`, you can try to start with the `podman` driver as follows:

.Start minikube with podman driver
[source,shell,subs="attributes+"]
----
minikube start [...] --driver podman
----

=== Install

In order to have an up-and-running instance of the {product_name} Operator you can use the following command:

.Install {product_name} Operator on Kubernetes
[source,shell,subs="attributes+"]
----
kubectl create -f https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/{operator_version}/operator.yaml
----

You can follow the deployment of the {product_name} Operator:

.Watch the {product_name} Operator pod
[source,shell,subs="attributes+"]
----
kubectl get pod -n sonataflow-operator-system --watch
----

A successful installation should have an output like this:

.Successful Installation Output
[source]
----
NAME                                                     READY   STATUS              RESTARTS   AGE
sonataflow-operator-controller-manager-948547ffd-sr2j2   0/2     ContainerCreating   0          6s
sonataflow-operator-controller-manager-948547ffd-sr2j2   1/2     Running             0          7s
sonataflow-operator-controller-manager-948547ffd-sr2j2   2/2     Running             0          20s
----

You can also follow the operator’s log:

.Watch the {product_name} Operator pod logs
[source,shell,subs="attributes+"]
----
kubectl logs deployment/sonataflow-operator-controller-manager -n sonataflow-operator-system -f
----

Once the operator is running, it will watch for new custom resources (CR) so that you can prepare your environment to be ready to create a new {product_name} application based on the definitions you will send to the operator.

=== Uninstall

To uninstall the {operator_name}, first you should remove all the object instances managed by it. Then, you can delete every object created during the installation.

To delete every object instance managed by the workflow in your cluster, you can run these series of commands:

.Delete every {product_name} object instances
[source,shell,subs="attributes+"]
----
kubectl delete --all workflow --all-namespaces
kubectl delete --all sonataflowbuild --all-namespaces
kubectl delete --all sonataflowplatform --all-namespaces
----

Alternatively, if you created everything under the same namespace, deleting the given namespace has the same outcome.

To uninstall the correct version of the operator, first you must get the current version by running:

.Getting the operator version
[source,shell,subs="attributes+"]
----
kubectl get deployment sonataflow-operator-controller-manager -n sonataflow-operator-system -o jsonpath="{.spec.template.spec.containers[?(@.name=='manager')].image}"

quay.io/kiegroup/kogito-serverless-operator-nightly:1.41.0
----

The operator manager image reflects the current operator's version. Replace the major and minor version names in the command below. For example, if the image version is `1.41.0` use `1.41` in the placeholder:

.Uninstalling the operator
[source,shell,subs="attributes+"]
----
kubectl delete -f https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/<version>.x/operator.yaml
----

[TIP]
====
If you're running a snapshot version, use this URL instead `https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/main/operator.yaml`.
====

== Additional resources

* xref:cloud/operator/known-issues.adoc[]
* xref:cloud/operator/developing-workflows.adoc[]

include::../../../pages/_common-content/report-issue.adoc[]
