= Installing the Knative Workflow Plugin
:compat-mode!:
// Metadata:
:description: Install the operator on Kubernetes clusters
:keywords: kogito, sonataflow, workflow, serverless, operator, kubernetes, minikube, openshift, containers
// links

*Prerequisites*

* You have first installed the link:{kn_cli_install_url}[Knative CLI].
* link:{docker_install_url}[Docker] or {podman_install_url}[Podman] is installed.

[proc-install-sw-plugin-kn-cli]]
== Installing the {product_name} plug-in for Knative CLI

You can use the {product_name} plug-in to set up your local workflow project quickly using Knative CLI. 

.Procedure
. Download the latest binary file, suitable for your environment, from the link:{kn_workflow_plugin_releases_url}[download] page.
. Install the `kn workflow` command as a plug-in of the Knative CLI using the following steps:
+
--
.. Rename the downloaded binary as follows:
+
`mv kn-workflow-linux-amd64 kn-workflow`
+
.. Make the binary file executable as follows:
+
`chmod +x kn-workflow`
+
[WARNING]
==== 
On Mac, some systems might block the application to run due to Apple enforcing policies. To fix this problem, check the *Security & Privacy* section in the *System Preferences* -> *General* tab to approve the application to run. For more information, see link:{apple_support_url}[Apple support article: Open a Mac app from an unidentified developer].
====
.. Copy the `kn-workflow` binary file to `/usr/local/bin`.
.. Run the following command to verify that `kn-workflow` plug-in is installed successfully:
+
`kn plugin list`
--

== Installing the Knative Workflow Plugin using the artifacts image

To install the Knative Workflow Plugin using the artifacts image you must follow this procedure:

*Start the `kn-workflow-cli-artifacts-rhel8` image*

[source, shell]
----
export KN_IMAGE=registry.redhat.io/openshift-serverless-1/logic-kn-workflow-cli-artifacts-rhel8:1.33.0

export KN_CONTAINER_ID=$(docker run -di $KN_IMAGE)
----

*Copy the Knative Workflow Plugin binary according to your environment*

.Binaries copy for `Linux` amd64 / arm64 architectures
[source, shell]
----
docker cp $KN_CONTAINER_ID:/usr/share/kn/linux_amd64/kn-workflow-linux-amd64.tar.gz kn-workflow-linux-amd64.tar.gz

docker cp $KN_CONTAINER_ID:/usr/share/kn/linux_arm64/kn-workflow-linux-arm64.tar.gz kn-workflow-linux-arm64.tar.gz
----

.Binaries copy for `macOS` amd64 / arm64 architectures
[source, shell]
----
docker cp $KN_CONTAINER_ID:/usr/share/kn/macos_amd64/kn-workflow-macos-amd64.tar.gz kn-workflow-macos-amd64.tar.gz

docker cp $KN_CONTAINER_ID:/usr/share/kn/macos_arm64/kn-workflow-macos-arm64.tar.gz kn-workflow-macos-arm64.tar.gz
----

.Binaries copy for `Windows` amd64 architecture
[source, shell]
----
docker cp $KN_CONTAINER_ID:/usr/share/kn/windows/kn-workflow-windows-amd64.zip kn-workflow-windows-amd64.zip
----

*Stop the Container*

[source, shell]
----
docker stop $KN_CONTAINER_ID

docker rm $KN_CONTAINER_ID
----

*Extract the selected Knative Workflow Plugin binary*

.Extract the binary example
[source,shell]
----
tar xvzf kn-workflow-linux-amd64.tar.gz <install_dir_path>
----

In the `<install_dir_path>`, you'll find the `kn` executable that you must rename to `kn-workflow`

[source,shell]
----
mv <install_dir_path>/kn <install_dir_path>/kn-workflow
----

[IMPORTANT]
====
Make sure that `<install_dir_path>` is included in your system PATH.
====

To verify that the installation was successful, you can execute the following command:
[source,shell]
----
kn workflow version
----
output:
[source,shell]
----
1.33.0
----
