= Use {smproductname} to isolate network traffic with {serverlessproductname}
:compat-mode!:
// Metadata:
:description: Use {smproductname} to isolate network traffic with {serverlessproductname}

// TODO

{smproductshortname} can be used to isolate network-traffic between "tenants" using {smproductshortname} `AuthorizationPolicy` resources. {serverlessproductname} can also leverage this, using several {smproductshortname} resources.


.High-level architecture
The high-level architecture consists of `AuthorizationPolicies` in the `knative-serving`, `knative-eventing` and the tenants namespaces, while all components are part of the {smproductshortname}. The respective `istio-proxy` sidecars take care of enforcing those rules to isolate traffic between tenants.

*Knative Serving*

image::service-mesh/multi-tenancy-service-mesh.drawio.svg[]

*Knative Eventing*

TODO pierdipi, please add your diagram here!


.Prerequisites

* You have access to an {product-title} account with cluster administrator access.

* You have created a project or have access to a project with the appropriate roles and permissions to create applications and other workloads in {product-title}.

* You have set up {serverlessproductname} and {smproductname} as documented in xref:./common-service-mesh-setup.adoc[]


.Securing the {smproductshortname}

. As in the set-up documentation, make sure that all your tenants are part of the same `ServiceMeshMemberRoll` object as members:
+
[source,yaml]
----
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
 name: default
 namespace: istio-system
spec:
 members:
   - knative-serving
   - knative-eventing
   - tenant-1
   - tenant-2
----
+
All the namespaces that are part of the Mesh must enforce mTLS in strict mode. This forces Istio to only accept connections with a client-certificate present and allows the `istio-proxy` to validate the origin using `AuthorizationPolicy`.
+
. For {serverlessproductname} internal components to work, the several `AuthorizationPolicies` are necessary in the `knative-serving` and the `knative-eventing` namespace. The necessary resources are available in link:https://github.com/openshift-knative/knative-istio-authz-chart/tree/main/setup[here]:

- `deny-all-by-default.yaml` denies all traffic that is not explicitly allowed in `knative-serving` and `knative-eventing`
- `allow-traffic-to-activator.yaml` allows traffic from `istio-system` and `knative-serving` to activator
- `allow-traffic-to-autoscaler.yaml` allows traffic from `knative-serving` to autoscaler
- `allow-probe-kafka-controller.yaml` allows health probes for kafka components in `knative-eventing`
- `allow-mt-channel-based-broker-to-channels.yaml` allows internal traffic for channel based brokers in `knative-eventing`
+
Make sure to apply all those rules to your cluster with
+
[source,terminal]
----
$ oc apply -f <filename>
----

. With this set up in place, cluster administrators can use their own `AuthorizationPolicies` to define which namespaces (tenants) can communicate with each other. Each namespace needs:
- One AuthorizationPolicy limiting directly incoming traffic in the tenants namespace
- One AuthorizationPolicy limiting incoming traffic via activator in the `knative-serving` namespace
- One AuthorizationPolicy allowing Kubernetes to call PreStopHooks on Knative Services
- One AuthorizationPolicy allowing cluster monitoring to… // TODO
+
As it is a cumbersome task to create all those policies by hand, you can use our link:https://github.com/openshift-knative/knative-istio-authz-chart[helm based generator] to create the necessary resources for each tenant:
+
[source,terminal]
.Create resources per tenant with helm
----
helm template oci://quay.io/pierdipi/knative-istio-authz-onboarding --version 0.1.0 --set "name=tenant-1" --set "namespaces={ns1, ns2}"
helm template oci://quay.io/pierdipi/knative-istio-authz-onboarding --version 0.1.0 --set "name=tenant-2" --set "namespaces={ns3, ns4}"
----
+
And apply the generated resources to your cluster:
+
[source,terminal]
----
$ oc apply -f <filename>
----
+
[NOTE]
====
The helm chart has several options that can be passed to configure the generated resources. Please refer to the link:https://github.com/openshift-knative/knative-istio-authz-chart/blob/main/values.yaml[values.yaml] for a full reference.
====


.Verifying the {smproductshortname}

 TODO

