// Module included in the following assemblies
// /functions/dev_guide/develop-quarkus.adoc

When an incoming request is received, functions are invoked with an instance of a permitted type of your choice. What the instance will contain depends on the invocation method:

.Function invocation options
[options="header",cols="d,d,m"]
|====
|Invocation method |What the instance will contain |Example of data
|HTTP POST request | JSON object in the body of the request |`{ "customerId": "0123456", "productId": "6543210" }`
|HTTP GET request | Data in the query string |`?customerId=0123456&productId=6543210`
|`CloudEvent` | JSON object in the `data` property |`{ "customerId": "0123456", "productId": "6543210" }`
|====

This is the signature of an example function that receives and processes purchase data, such as the `customerId` and `productId` data in the table:

.Example
[source,java]
----
public class Functions {
    @Funq
    public void processPurchase(Purchase purchase) {
        // process the purchase
    }
}
----

The corresponding `Purchase` JavaBean class that contains the purchase data might look like this:

.Example
[source,java]
----
public class Purchase {
    private long customerId;
    private long productId;
    // getters and setters
}
----
