// Module included in the following assemblies
//
// functions/user_guide/develop-quarkus.adoc

[id="return-values-quarkus_{context}"]
= Return values

Functions can return an instance of:

* any type from the permitted types
* the `Uni<T>` type, where the `<T>` type parameter can be of any type from the permitted types

The `Uni<T>` type might be useful when the function calls asynchronous APIs.

The returned object is serialized in the same format as the received object:

* If the function received an HTTP request, then the returned object is sent in the body of an HTTP response.
* If the function received `CloudEvent` in binary encoding, then the returned object is sent in the `data` property of a binary-encoded `CloudEvent`.

This is an example function for getting a list of purchases:

.Example
[source,java]
----
public class Functions {
    @Funq
    public List<Purchase> getPurchasesByName(String name);
}
----

* Invoking this function through an HTTP request produces an HTTP response, the body of which contains a list of purchases.
* Invoking this function through an incoming `CloudEvent` produces a `CloudEvent` response with a list of purchases in the `data` property.
