= {product_name} Applications in Cloud
:compat-mode!:
// Metadata:
:description: Workflow Applications in Kubernetes
:keywords: cloud, kubernetes, docker, image, podman, openshift, pipelines
// other

{product_name} is evolving as platform to build and deploy workflow applications in Kubernetes clusters.

You have two options to deploy your workflow applications: either as a full Quarkus project or using the {operator_name}.

The cards below list all features included in the platform to deploy workflow applications either with Quarkus or the Operator.

[NOTE]
====
Eventually these two options will converge, the {operator_name} will also be able to handle full Quarkus projects. So if you opt in to use Quarkus now and manually deploy your workflows, bear in mind that it's on the project's roadmap to integrate the Quarkus experience with the Operator.
====

[.card-section]
== Kubernetes with Quarkus

For Java developers, you can use Quarkus and a few add-ons to help you build and deploy the application in a Kubernetes cluster. {product_name} also generates basic Kubernetes objects YAML files to help you getting started. The application should be managed by a Kubernetes administrator.

[.card]
--
[.card-title]
xref:cloud/quarkus/build-workflow-image-with-quarkus-cli.adoc[Building workflow images using Quarkus CLI]
[.card-description]
Learn how to build images for your workflow applications using Quarkus CLI
--

[.card]
--
[.card-title]
xref:cloud/quarkus/kubernetes-service-discovery.adoc[Kubernetes service discovery in {product_name}]
[.card-description]
Learn what is and how the Kubernetes service discovery for workflow application configuration works
--

[.card]
--
[.card-title]
xref:cloud/quarkus/deploying-on-minikube.adoc[Deploying your {product_name} application on Minikube]
[.card-description]
Learn how to deploy your workflow application on Minikube for local tests and development
--

[.card]
--
[.card-title]
xref:cloud/quarkus/deploying-on-kubernetes.adoc[Deploying your {product_name} application on Kubernetes]
[.card-description]
Learn how to deploy your workflow application on Kubernetes
--

[.card-section]
== Kubernetes with the Operator

For developers that are looking for a native Kubernetes approach where you can model workflows using YAML definitions and directly deploy them, you can use the {operator_name}. The operator registers a new Kubernetes resource in the cluster to manage your workflow development iteration cycle and composition of services and events. The application is managed by the operator.

[.card]
--
[.card-title]
xref:cloud/operator/install-serverless-operator.adoc[]
[.card-description]
Learn how to install the {operator_name} in a Kubernetes cluster
--

[.card]
--
[.card-title]
xref:cloud/operator/developing-workflows.adoc[]
[.card-description]
Learn how to deploy a workflow for development purposes
--

[.card]
--
[.card-title]
xref:cloud/operator/configuring-workflows.adoc[]
[.card-description]
Learn how to configure workflows deployed with {operator_name}
--

[.card]
--
[.card-title]
xref:cloud/operator/workflow-status-conditions.adoc[]
[.card-description]
Learn to interpret the workflow resource status conditions
--

[.card]
--
[.card-title]
xref:cloud/operator/build-and-deploy-workflows.adoc[]
[.card-description]
Learn how to build and deploy workflow services with {operator_name}
--

[.card]
--
[.card-title]
xref:cloud/operator/known-issues.adoc[]
[.card-description]
Learn about the known issues and feature roadmap of the {operator_name}
--
