// This module is included in the following assemblies:
//
// assembly_knative-v-0-5-0-OCP-4x.adoc

[id='knative-v-0-5-0-ocp-4x_{context}']
= Knative v0.5.0 on an OpenShift 4.0 cluster

NOTE: The functionality introduced by Knative on an OpenShift cluster is preview only. Red Hat support is not provided, and this release should not be used in a production environment.

IMPORTANT: This Knative on OpenShift preview is only available by using the OpenShift 4.0 developer preview. You will require a Red Hat Developers login to try this. Visit link:https://try.openshift.com/[try.openshift.com] for getting started information.

You will need cluster administrator privileges to install and use Knative on an OpenShift cluster.

NOTE: This release includes upstream Knative Serving `v0.5.1`, Knative Eventing `v0.5.0` and Knative Build `v0.5.0`.


=== Supported platform version

IMPORTANT: Installation requires the OpenShift version `0.16.1` installer or later. Using the link:https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/)[latest version installer] is recommended.  

[cols="50,50"]
|===
|** Platform**     | **Supported versions**   
| OpenShift    | 4.0 Developer Preview
|===

NOTE: Long-running clusters are not supported in this release.[latest version installer]

