// This module is included in the following assemblies:
//
// assembly_knative-v-0-5-0-OCP-4x.adoc


[id='knative-v-0-5-0-installing-knative-ocp-using-script-4x_{context}']
= Installing Knative v0.5.0 on an OpenShift cluster 4.0 using the script provided

NOTE: This Knative v0.5.0 on OpenShift preview is only available by using the OpenShift 4.0 developer preview. 


.Prerequisites
* You will require a Red Hat Developers login to try this. 
* Using 4.0 clusters with Knative requires visiting link:https://try.openshift.com/[try.openshift.com]

IMPORTANT: Installation requires the OpenShift version `0.16.1` installer or later. Using the link:https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/)[latest version installer] is recommended.  


.Procedure
1. Login to the cluster using your admin credentials.

   `oc login <admin-credentials>`
   
2. Clone the `knative-operators` repository.

```
   git clone https://github.com/openshift-cloud-functions/knative-operators
   cd knative-operators/
   git fetch --tags  
   git checkout openshift-v0.4.0      
```

3. Navigate to the newly cloned repository and run the `install.sh` script.

   `./etc/scripts/install.sh`  

NOTE: The `install.sh` script can time-out waiting for the Istio operator to complete, and you may receive an `ERROR: Timed out` message. If the `install.sh` script fails to install Istio, run the script again after it times out.

4. Once the script starts, you will see the following warning and prompt.

```
   WARNING: This script will attempt to install Istio, Knative, and OLM in your Kubernetes/OpenShift cluster.
    
   If targeting OpenShift, a recent version of 'oc' should be available in your PATH. Otherwise, 'kubectl' will be used.

   Pass -q to disable this prompt
 
   Enter to continue or Ctrl-C to exit:

```

5. Press Enter to continue.