= Integrating with Red Hat OpenShift Application and Data Services
:compat-mode!:
// Metadata:
:description: {serverless_logic_web_tools_name} Red Hat OpenShift Application and Data Services integration
:keywords: kogito, workflow, serverless, editor, web, tools, settings, red hat, application, data, services, integration

Some of the features in {serverless_logic_web_tools_name} require integration with Red Hat OpenShift Application and Data Services. Consider uploading OpenAPI specifications to a service registry and fetching its service functions as examples of integration with Red Hat OpenShift Application and Data Services.

This document describes how you can configure the required settings to complete the integration with Red Hat OpenShift Application and Data Services.

[[proc-create-service-account-serverless-logic-web-tools]]
== Creating a service account in Red Hat OpenShift application and Data Services

You can create or use a service account from your Red Hat OpenShift Application and Data Services console and add the service account to the {serverless_logic_web_tools_name}.

.Prerequisites
* You have access to the Red Hat OpenShift Application and Data Services console.

.Procedure
. To create a service account in Red Hat Openshift Application and Data Services, perform the following steps:
+
--
[NOTE]
====
You can skip this step if you already have a service account.
====
.. Go to link:{openshift_application_data_services_service_account_url}[Service Accounts | Red Hat OpenShift Application and Data Services].
.. Click *Create service account*.
.. In the *Create a service account* window, enter a service account name in the *Short description* field.
.. Click *Create*.
+
A modal displaying your *Client ID* and *Client Secret* appears.
.. Copy and save the Client ID and Client Secret.
.. Check the *I have copied the client ID and secret* checkbox and click *Close*.
--

. If you already have a service account, find your *Client ID* and *Client Secret*.
. In the {serverless_logic_web_tools_name}, click the *Cogwheel* (⚙️) on the top-right corner and go to the *Service Account* tab.
. Click on the *Add service account* button and a window will be shown.
. Enter your *Client ID* and *Client Secret* in the respective fields.
. Click *Apply*.
+
The content in the *Service Account* tab updates and displays *Your Service Account information is set* message.


[[proc-create-service-registry-serverless-logic-web-tools]]
== Creating a Service Registry in Red Hat OpenShift application and Data Services

You can create or use a Service Registry instance from your Red Hat OpenShift Application and Data Services console and add the Service Registry to {serverless_logic_web_tools_name}.

.Prerequisites
* You have access to the Red Hat OpenShift Application and Data Services console.
* You have created a service account.
+
For information about creating a service account, see <<proc-create-service-account-serverless-logic-web-tools, Creating a service account in Red Hat OpenShift application and Data Services>>.

.Procedure
. To create a Service Registry instance in Red Hat Openshift Application and Data Services console, perform the following steps:
+
--
[NOTE]
====
You can skip this step if you already have a Service Registry instance.
====
.. Go to link:{openshift_application_data_services_service_registry_url}[Service Registry | Red Hat OpenShift Application and Data Services].
.. Click *Create Service Registry instance* button.
.. In the *Create a Service Registry instance* window, enter a Service Registry instance name and click *Create*.
+
The list of Service Registry instances updates with your instance.
.. Find the Service Registry instance you created in the list and click on the instance.
.. Go to the *Settings* tab and click on *Grant access*.
.. In the drop-down, select the service account you created in the previous procedure.
.. Select a role for your service account.
+
[IMPORTANT]
====
You must select the role as Manager or Administrator to have the read and write access.
====

.. Click *Save*.
.. Click on the menu on the top-right corner of the screen.
.. Click *Connection*.
+
A drawer opens containing the required connection and authentication information.

.. Copy the value of *Core Registry API*.
--

. If you already have a Service Registry, find the value of *Core Registry API* of your Service Registry.
. In the {serverless_logic_web_tools_name} web application, click the *Cogwheel* (⚙️) on the top-right corner and go to the *Service Registry* tab.
. Click on the *Add service registry* button and a window will be shown.
. Enter a name for your registry.
+
You can enter the same name that you used while creating the Service Registry instance.

. Enter the value of *Core Registry API* and click *Apply*.
+
The content in the *Service Registry* tab updates and displays *Your Service Registry information is set* message.

include::../../../pages/_common-content/report-issue.adoc[]