= Invoking Knative services from {context}
:compat-mode!:
// Metadata:
:description: Explain what is and how the Knative service discovery works
:keywords: kogito, workflow, quarkus, serverless, service-discovery, knative
// envs for common content
:environment_prereq: Minikube is installed
:kubectl_prereq: command-line tool is installed. Otherwise, Minikube handles it.

This document describes how to call Knative services using {context} custom functions. The procedure described in this document is based on the link:{kogito_sw_examples_url}/serverless-workflow-custom-function-knative[`serverless-workflow-custom-function-knative`] example application.

For more details about the Knative custom function, see xref:core/custom-functions-support.adoc#knative-custom-function[Custom functions for your {context} service].

.Prerequisites

include::../cloud/common/_prerequisites.adoc[]

* You have the link:{kogito_sw_examples_url}/serverless-workflow-custom-function-knative/custom-function-knative-service[custom-function-knative-service] project deployed on Knative. For more information on how to deploy a Quarkus project to Knative, see the https://quarkus.io/guides/deploying-to-kubernetes[Quarkus Kubernetes extension documentation].

.Procedure

. Add the `knative-serving` add-on dependency to your link:{kogito_sw_examples_url}/serverless-workflow-custom-function-knative/workflow[workflow] project.
+
--

[source,xml]
----
<dependency>
    <groupId>org.kie.kogito</groupId>
    <artifactId>kogito-addons-quarkus-knative-serving</artifactId>
</dependency>
----

--

. Discover the name of the Knative service that your workflow will invoke. In a terminal window, run the following command:
+
--

[source,bash]
----
kn service list
----

You should see an output like:

[source,bash]
----
NAME                              URL                                                                      LATEST                                  AGE     CONDITIONS   READY   REASON
custom-function-knative-service   http://custom-function-knative-service.default.10.109.169.193.sslip.io   custom-function-knative-service-00001   3h16m   3 OK / 3     True
----

Save the Knative service name (`custom-function-knative-service`) to use it in the next step.

--

. Declare the Knative {context} custom function. In the `functions` section of your workflow, add the following:

+
--

[source,json]
----
{
  "name": "greet", <1>
  "type": "custom", <2>
  "operation": "knative:custom-function-knative-service", <3>
  "metadata": {
    "path": "/function" <4>
  }
}
----

<1> The name of the {context} function
<2> Indicates that this function is a custom one
<3> Indicates that your custom function is of type `knative` and it will invoke the `custom-function-knative-service` service.
<4> The resource path you want to access

--

. Invoke the declared function. In an `operation` state, add an `action` that references the function you declared in the previous step like the following:

+
--

[source,json]
----
"actions": [
  {
    "functionRef": {
      "refName": "greet", <1>
      "arguments": { <2>
        "name": ".name"
      }
    }
  }
]
----
<1> Function's name
<2> The payload that should be sent in the request

--

. Deploy your workflow service to Knative. For more information on how to deploy a {product_name} {context} project to Knative, see the xref:cloud/deploying-on-kubernetes.adoc[Deploying on Kubernetes].

. Submit a request to the workflow service

+
--
[source,bash]
----
curl -X 'POST' \
  '<URL>/knativeFunction' \ <1>
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{ "name": "Kogito" }'
----

<1> Replace `<URL>` with the URL of your deployed workflow service

You should see an output like (`id` will change):

[source,json]
----
{"id":"87cf8275-782d-4e0b-a9be-a95f95c9c190","workflowdata":{"name":"Kogito","greeting":"Greetings from Serverless Workflow, Kogito"}}
----

--

== Additional resources

* xref:core/custom-functions-support.adoc[Custom functions for your {context} service]
* xref:cloud/deploying-on-minikube.adoc[Deploying your Serverless Workflow application on Minikube]
* xref:cloud/deploying-on-kubernetes.adoc[Deploying your Serverless Workflow application on Kubernetes]

include::../_common-content/report-issue.adoc[]