= Log Sink
:compat-mode!:
// Metadata:
:description: Log Sink in {serverlessproductname}

This page describes how to use the _Log Sink Kamelet_ with the `IntegrationSink` API for Eventing in {serverlessproductname}. This sink is useful for debugging purposes.

[IMPORTANT]
====
{serverlessproductname} `IntegrationSink` is a Developer Preview feature only.

Developer Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete.
Red Hat does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Developer Preview features, see https://access.redhat.com/support/offerings/devpreview/.
====

== Log Sink Example

Below is an `IntegrationSink` that logs all data that it receives:

[source,yaml]
----
apiVersion: sinks.knative.dev/v1alpha1
kind: IntegrationSink
metadata:
  name: integration-log-sink
  namespace: knative-samples
spec:
  log:
    showHeaders: true
    level: INFO
----

Inside of the `log` object we define the logging `level` and define to also show (HTTP) headers it received.

More details about the Apache Camel Kamelet https://camel.apache.org/camel-kamelets/latest/log-sink.html[log-sink].
