= Configuring OpenAPI Services Endpoints

:compat-mode!:
// Metadata:
:description: Configuring OpenAPI services endpoints in Serverless Workflow
:keywords: kogito, workflow, quarkus, serverless, openapi, orchestration
// links:
:quarkus-profiles-url: https://quarkus.io/guides/config-reference#profiles

This document describes how you can configure OpenAPI service endpoints in {product_name}.

[[con-config-openapi-services-endpoints]]
== Overview 

{product_name} leverages MicroProfile REST Client to invoke OpenAPI services. Therefore, you can configure the OpenAPI services by following the MicroProfile Config specification. For the list of properties to configure in the MicroProfile REST Client specification, see link:https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#mpconfig[Support for MicroProfile Config] in MicroProfile REST Client documentation.

{product_name} follows the strategy defined in the `kogito.sw.operationIdStrategy` property to generate the REST Client. The possible values of the `kogito.sw.operationIdStrategy` property include:

* `FILE_NAME`(Default value): {product_name} uses the configuration key based on the OpenAPI document file name as shown in the following example:
+
--
.Example property
[source,properties]
----
quarkus.rest-client.stock_portfolio_svc_yaml.url=http://localhost:8282/
----

In the previous example, {product_name} uses `stock_portfolio_svc_yaml` as configuration key as the OpenAPI document is available at `src/main/resources/openapi/stock-portfolio-svc.yaml`.
--

* `FULL_URI`: {product_name} uses the full URI path as configuration key as shown in the following example:
+
--
.Example Serverless Workflow
[source,json]
----
{
    "id": "myworkflow",
    "functions": [
        {
          "name": "myfunction",
          "operation": "https://my.remote.host/apicatalog/apis/123/document" <1>
        }
    ]
    ...
}
----
<1> URI path of the OpenAPI document

.Example property
[source, properties]
----
quarkus.rest-client.apicatalog_apis_123_document.url=http://localhost:8282/
----

In the previous example, {product_name} uses `apicatalog_apis_123_document` as configuration key.
--

* `FUNCTION_NAME`: {product_name} uses the workflow ID and the function name that references the OpenAPI document as shown in the following examples:
+
--
.Example Serverless Workflow
[source,json]
----
{
    "id": "myworkflow",
    "functions": [
        {
          "name": "myfunction",
          "operation": "https://my.remote.host/apicatalog/apis/123/document"
        }
    ]
    ...
}
----

.Example property
[source, properties]
----
quarkus.rest-client.myworkflow_myfunction.url=http://localhost:8282/
----

In the previous example, {product_name} uses `"myworkflow_myfunction"` as configuration key.
--

* `SPEC_TITLE`: {product_name} uses the value of `info.title` in the OpenAPI document as shown in the following examples:
+
--
.Example OpenAPI document
[source,yaml]
----
---
openapi: 3.0.3
info:
  title: stock-service API
  version: 2.0.0-SNAPSHOT
paths:
  /stock-price/{symbol}:
...
----

.Example property
[source, properties]
----
quarkus.rest-client.stock-service_API.url=http://localhost:8282/
----

In the previous example, {product_name} uses `stock-service_API` as configuration key.
--

[NOTE]
====
A Kubernetes service endpoint can be used as a service URL if the target service is within the same cluster, such as `http://myservice.mynamespace.cluster.svc.local`.
====

=== Using URI alias

As an alternative to `kogito.sw.operationIdStrategy`, you can assign an alias name to a URI by using `workflow-uri-definitions` custom link:{spec_doc_url}#extensions[extension]. Then you can use that alias as configuration key and in function definitions.

.Example workflow
[source,json]
----
"extensions" : [ {
      "extensionid": "workflow-uri-definitions",
      "definitions": {
        "remoteCatalog": "https://my.remote.host/apicatalog/apis/123/document",
       }
     }
  ], 
  "functions": [
        {
          "name": "operation1",
          "operation": "remoteCatalog#operation1"
        }, 
        {
          "name": "operation2",
          "operation": "remoteCatalog#operation2"
        }
    ]
----

.Example property
[source, properties]
----
quarkus.rest-client.remoteCatalog.url=http://localhost:8282/
----

In the previous example, {product_name} uses `remoteCatalog` as configuration key.




== Additional resources

* xref:service-orchestration/orchestration-of-openapi-based-services.adoc[Orchestrating the OpenAPI services]
* link:{quarkus-profiles-url}[Quarkus configuration guide]
* xref:service-orchestration/troubleshooting.adoc[]

include::../../pages/_common-content/report-issue.adoc[]