= CNCF Serverless Workflow specification
:compat-mode!:
// Metadata:
:description: CNCF Serverless Workflow Specification Support
:keywords: kogito, workflow, serverless, cncf, specification
// links
:quarkus_config_guide_url: https://quarkus.io/guides/config-reference

This document describes the information about the implementation of the link:{spec_website_url}[Cloud Native Computing Foundation (CNCF) Serverless Workflow] specification. {product_name} implements version link:{spec_doc_url}[{spec_version}] of the Serverless Workflow specification.

The following table shows the implementation status for each Serverless Workflow specification feature.

[NOTE]
====
{product_name} does not support link:{spec_doc_url}#Retry-Definition[Retries], link:{spec_doc_url}#sleep-state[Sleep State], and link:{spec_doc_url}#workflow-timeouts[Timeouts] features of Serverless Workflow specification.
====

.Implementation status icons
[cols="50%,50%", options="header"]
|===
| Icon | Description

| emoji:full_moon[]
| Fully implemented feature and compliant with the Serverless Workflow specification

| emoji:last_quarter_moon[]
| Partially implemented feature

| emoji:construction[]
| Not implemented

|===

.Implementation status of the Serverless Workflow specification features
[cols="35%,30%,35%", options="header"]
|===
| Feature | Status | Reference

| <<states>>
| emoji:full_moon[]
| link:{spec_doc_url}#workflow-states[Workflow States]

| <<functions>>
| emoji:last_quarter_moon[]
| link:{spec_doc_url}#Function-Definition[Function Definition]

| <<events>>
| emoji:last_quarter_moon[]
| link:{spec_doc_url}#Event-Definition[Event Definition]

| <<workflow_data>>
| emoji:full_moon[]
| link:{spec_doc_url}#Workflow-Data[Workflow Data]

| <<expressions>>
| emoji:full_moon[]
| link:{spec_doc_url}#Workflow-Expressions[Workflow Expressions]

| <<error_handling>>
| emoji:full_moon[]
| link:{spec_doc_url}#Workflow-Error-Handling[Workflow Error Handling]

| <<retries>>
| emoji:construction[]
| link:{spec_doc_url}#Retry-Definition[Retry Definition]

| <<timeouts>>
| emoji:construction[]
| link:{spec_doc_url}#workflow-timeouts[Workflow Timeouts]

| <<compensation>>
| emoji:full_moon[]
| link:{spec_doc_url}#Workflow-Compensation[Workflow Compensation]

| <<constants>>
| emoji:full_moon[]
| link:{spec_doc_url}#workflow-constants[Workflow Constants]

| <<secrets>>
| emoji:full_moon[]
| link:{spec_doc_url}#workflow-secrets[Workflow Secrets]
|===

[[states]]
== States

The link:{spec_doc_url}#parallel-state[Parallel State] of the workflow states feature works in a single thread. This means that a Parallel State does not create one thread per branch, simulating an actual parallel behavior.

[NOTE]
====
{product_name} does not support the link:{spec_doc_url}#sleep-state[Sleep State] feature. However, this feature will be supported in a future release.
====

The following table shows all the workflow states that {product_name} supports in the Serverless Workflow specification {spec_version} version:

.Workflow States implementation status
[cols="35%,30%,35%", options="header"]
|===
| State | Status | Reference

| Event
| emoji:full_moon[]
| link:{spec_doc_url}#Event-State[Event State]

| Operation
| emoji:full_moon[]
| link:{spec_doc_url}#Operation-State[Operation State]

| Switch
| emoji:full_moon[]
| link:{spec_doc_url}#Switch-State[Switch State]

| Sleep
| emoji:construction[]
| link:{spec_doc_url}#sleep-state[Sleep State]

| Parallel
| emoji:last_quarter_moon[]
| link:{spec_doc_url}#Parallel-State[Parallel State]

| Inject
| emoji:full_moon[]
| link:{spec_doc_url}#Inject-State[Inject State]

| ForEach
| emoji:full_moon[]
| link:{spec_doc_url}#ForEach-State[ForEach State]

| Callback
| emoji:full_moon[]
| link:{spec_doc_url}#Callback-State[Callback State]
|===

[[functions]]
== Functions

The following table shows the status of the workflow functions that {product_name} supports:

.Workflow Functions implementation status
[cols="35%,30%,35%", options="header"]
|===
| Function | Status | Reference

| REST
| emoji:full_moon[]
| link:{spec_doc_url}#using-functions-for-restful-service-invocations[Using Functions for RESTful Service Invocations]

| RPC
| emoji:full_moon[]
| link:{spec_doc_url}#using-functions-for-rpc-service-invocations[Using Functions for RPC Service Invocations]

| Expression
| emoji:full_moon[]
| link:{spec_doc_url}#using-functions-for-expression-evaluation[Using Functions for Expression Evaluation]

| Async API
| emoji:construction[]
| link:{spec_doc_url}#using-functions-for-async-api-service-invocations[Using Functions for Async API Service Invocations]

| GraphQL
| emoji:construction[]
| link:{spec_doc_url}#using-functions-for-graphql-service-invocations[Using Functions for GraphQL Service Invocations]

| OData
| emoji:construction[]
| link:{spec_doc_url}#using-functions-for-odata-service-invocations[Using Functions for OData Service Invocations]

| Custom
| emoji:full_moon[]
| link:{spec_doc_url}#defining-custom-function-types[Defining custom function types]
|===

For additional functions, the Serverless Workflow specification support the `custom` function type, such as `sysout` and `java`. For more information about these custom function types, see xref:core/custom-functions-support.adoc[Custom functions for your {context} service].

[[events]]
== Events

{product_name} supports events of the workflow model as defined in the link:{spec_doc_url}#Event-Definition[Serverless Workflow specification definition], except the following:

* `resultEventRef` property in link:{spec_doc_url}#eventref-definition[`EventRefDefinition`] is not implemented and, if specified, this property is ignored. Same functionality can be achieved by using xref:eventing/working-with-callbacks.adoc[Callback] state.
* link:{spec_doc_url}#correlation-definition[Correlation] has limited support, that evaluates correlation rules matching a single event consumed per time with a workflow instance. The correlation among `N` different events to be consumed and matched with a workflow instance is not supported in {product_name}. For more information about event correlation, see xref:eventing/event-correlation-with-workflows.adoc[Event correlation in {context}].

[[workflow_data]]
== Serverless Workflow data

{product_name} supports the implementation of the data manipulation feature using `jq` (default) or `jsonpath` expressions.

`jsonpath` expressions can have limitations in specific scenarios of complex data manipulation. For more information, see link:{spec_doc_url}#workflow-data[Workflow Data] section in the Serverless Workflow specification documentation.

{product_name} also supports data filtering. For more information about the data filtering, see link:{spec_doc_url}#state-data-filters[State data filters] section in the Serverless Workflow specification documentation.

[[expressions]]
== Expressions

{product_name} supports `jq` or `jsonpath` to define the workflow expressions. `jq` is the default expression language, however, if you want to use `jsonpath`, set the `expressionLang` attribute in the workflow definition as shown in the following example:

.Example of changing the default expression language
[source,json]
----
{
  "id": "myworkflow",
  "version": "1.0",
  "expressionLang": "jsonpath",
  "name": "Workflow example",
  "description": "An example of how to use jsonpath expressions"
}
----

[WARNING]
====
`jsonpath` expression is not recommended because of the limitations of the language for data manipulation. Instead, you can use `jq` in various use cases.
====


[[error_handling]]
== Error handling

{product_name} supports the error handling feature as described in the link:{spec_doc_url}#workflow-error-handling[Serverless Workflow specification definition].

For more information about error handling, see xref:core/understanding-workflow-error-handling.adoc[Error handling in {context}].

[[retries]]
== Retries

{product_name} does not support Retries feature, however, it will be implemented in a future release.

Alternatively, you can use xref:core/understanding-workflow-error-handling.adoc[Error handling in {context}].

[[timeouts]]
== Timeouts

{product_name} does not support Timeouts feature, however, it will be implemented in a future release.

[[compensation]]
== Compensation

{product_name} supports workflow compensation as described in the link:{spec_doc_url}#Workflow-Compensation[Serverless Workflow specification definition].

For more information about compensations, see xref:use-cases/orchestration-based-saga-pattern.adoc[Saga orchestration example in {context}].

[[constants]]
== Constants

{product_name} supports workflow constants as described in the link:{spec_doc_url}#workflow-constants[Serverless Workflow specification definition].

[[secrets]]
== Secrets

{product_name} supports workflow secrets as described in the link:{spec_doc_url}#workflow-secrets[Serverless Workflow specification definition].

[IMPORTANT]
====
Secrets are associated with the link:{quarkus_config_guide_url}[Quarkus Configuration] module. This means that any form of configuration that Quarkus supports is also supported in {product_name}.
====

//Guide not available currently (DP1)
//For more information, see xref:core/accessing-workflow-metainformation-in-runtime.adoc[Accessing Serverless Workflow Metainformation].

== Additional resources

* xref:getting-started/create-your-first-workflow-service.adoc[Creating your first workflow service]
* xref:getting-started/getting-familiar-with-our-tooling.adoc[Getting familiar with {context} tooling]

include::../../pages/_common-content/report-issue.adoc[]
