= Creating and running workflow projects using KN CLI and Visual Studio Code

This guide showcases using the Knative Workflow CLI plugin and Visual Studio code to create & run {product_name} projects.

.Prerequisites
* You have setup your environment according xref:getting-started/preparing-environment.adoc#proc-minimal-local-environment-setup[minimal environment setup] guide.
* Install https://k9scli.io/[k9scli.io] for easier inspection of your application resources in cluster. This is optional, you can use any tool you are fimiliar with in this regard. 

[[proc-creating-app-with-kn-cli]]
== Creating a workflow project with Visual Studio Code and KN CLI

Use the `create` command with kn workflow to scaffold a new SonataFlow project.

* Navigate to you development directory and create your project.
[source,bash]
----
kn workflow create -n my-sonataflow-project
----
* This will create a folder with name `my-sonataflow-project` and a sample workflow `workflow.sw.json`
[source,bash]
----
cd ./my-sonataflow-project
----
* Open the folder in Visual Studo Code and examine the created `workflow.sw.json` using our extension.

Now you can run the project and execute the workflow.

[[proc-running-app-with-kn-cli]]
== Running a Workflow project with Visual Studio Code and KN CLI

Use the `run` command with kn workflow to build and run the {product_name} project in local development mode.

* Run the project.  
[source,bash]
----
kn workflow run
----
* The Development UI wil be accesible at `localhost:8080/q/dev`
* You can now work on your project. Any changes will be picked up by the hot reload feature.
* See xref:testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc[Workflow instances] guide on how to run workflows via Development UI.
* Once you are done developing your project navigate to the terminal that is running the `kn workflow run` command and hit `Ctlr+C` to stop the development environment.

To deploy the finished project to a local cluster, proceed to the next section.

[[proc-deploying-app-with-kn-cli]]
== Deploying a workflow project with Visual Studio Code and KN CLI

Use the `deploy` command with kn workflow to deploy the {product_name} project into your local cluster.

* Deploy to cluster
[source,bash]
----
kn workflow deploy --namespace my-sf-application
----
* Using k9s cli you can examine your deployment.
* In a separate bash instance create a port mapping:
+
[tabs]
====
Minikube::
+
--
[source,shell]
----
minikube service hello --namespace my-sf-application --url
----
* Use this URL to access your workflow instances using the Developer UI
** <RETURNED_URL>{sonataflow_devmode_devui_url}/workflowInstances
--
Kind::
+
--
[source,shell]
----
# Execute
kubectl get services -n my-sf-application

# You should see output like this, note the ports
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)            AGE
hello        ClusterIP   10.96.0.1    <none>        <RANDOM_PORT>/80   39s

# Execute
kubectl port-forward service/hello <RANDOM_PORT>:80 -n my-sf-application

----
--
====

* To update the image run the `deploy` again, note that this may take some time.
* To stop the deployment, use the `undeploy` command:
[source,bash]
----
kn worklow undeploy --namespace my-sf-application
----
* You can validate your pod is terminating using k9s cli.

[[proc-testing-application]]
== Testing your workflow application

To test your workflow application you can use any capable REST client out there. All that is needeed is the URL of your deployed worklow project.

.Prerequisites
* You have your workflow project deployed using <<proc-deploying-app-with-kn-cli>> and you have the URL where it is deployed handy.

.Testing your workflow application
* To test your workflow project, access the Swagger UI on `<URL>/q/swagger-ui` to examine available endpoints.
* In order to execute the workflow once, run: 
[source,bash]
----
curl -X 'POST' \
  '<URL>/hello' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "workflowdata": {}
}'
----
* To examine executed instance you can use the GraphQL UI by navigating to
`<URL>/q/graphl-ui`.


== Additional resources

* xref:testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc[]
* xref:getting-started/getting-familiar-with-our-tooling.adoc[]
* xref:service-orchestration/orchestration-of-openapi-based-services.adoc[]
* xref:cloud/operator/developing-workflows.adoc[]

include::../../pages/_common-content/report-issue.adoc[]

ifeval::["{kogito_version_redhat}" != ""]
include::../../pages/_common-content/downstream-project-setup-instructions.adoc[]
endif::[]