= Environment setup

This guide lists the different ways to set up your environment for {product_name} development. 
If you are new, start with the minimal one.

.Prerequisites
* A machine with at least 8GB memory and a link:https://en.wikipedia.org/wiki/Multi-core_processor[CPU with 8 cores]

[[proc-minimal-local-environment-setup]]
== Minimal local environment setup

Recommended steps to set up your local development environment. By completing these steps you are able to
start the development on your local machine using our guides.

.Procedure
. Install link:{docker_install_url}[Docker] or link:{podman_install_url}[Podman].
. Install link:{minikube_start_url}[minikube] or link:{kind_install_url}[kind].
. Install link:{kubectl_install_url}[Kubernetes CLI].
. Install link:{knative_quickstart_url}[Knative using quickstart]. This will also set up Knative Serving and Eventing for you and the cluster should be running.
. Install the xref:cloud/operator/install-serverless-operator.adoc#_sonataflow_operator_manual_installation[{operator_name} manually].
. Install xref:testing-and-troubleshooting/kn-plugin-workflow-overview.adoc[Knative Workflow CLI].
. Install link:{visual_studio_code_url}[Visual Studio Code] with link:{visual_studio_code_swf_extension_url}[our extension] that simplifies development of workflows by providing visual aids and auto-complete features.

[[proc-starting-cluster-fo-local-development]]
== Starting the cluster for local development

If you have used link:{knative_quickstart_url}[Knative using quickstart] guide, your selected cluster should be running and properly configured to work with our guides.

Please note, that if the Knative quickstart procedure is not used, you need to install Knative Serving and Eventing manually. See <<proc-additional-options-for-local-environment>>.


.To start up the selected cluster without quickstart, use the following command:
[tabs]
====
Minikube with Docker::
+
--
.Configure and startup minikube with Docker
[source,shell]
----
# Set a driver and container runtime
minikube config set driver docker
minikube config set container-runtime docker

# Start the cluster
# Set the memory to at least 4096, increase to 6144 or 8192 if possible
minikube start --cpus 4 --memory 4096 --addons registry --addons metrics-server --insecure-registry "10.0.0.0/24" --insecure-registry "localhost:5000"

# Set the active profile
minikube profile knative
----
--
Minikube with Podman::
+
--
.Configure and startup minikube with Podman
[source,shell]
----
# Set a driver and container runtime
minikube config set driver podman
minikube config set container-runtime podman

# Start the cluster
# Set the memory to at least 4096, increase to 6144 or 8192 if possible
minikube start --cpus 4 --memory 4096 --addons registry --addons metrics-server --insecure-registry "10.0.0.0/24" --insecure-registry "localhost:5000"

# Set the active profile
minikube profile knative
----
--
Kind::
+
--
.Start a kind cluster
[source,shell]
----
kind create cluster
----
--
====

[[proc-advanced-local-environment-setup]]
== Advanced local environment setup

If you are interested in our Java and Quarkus development path, consider completing this procedure in addition to the
<<proc-minimal-local-environment-setup>>. By completing these steps you are able to start the development of applications on your local machine using our xref:use-cases/advanced-developer-use-cases/index.adoc[advanced developer guides].

.Procedure
. Install link:{openjdk_install_url}[OpenJDK] {java_min_version} and configure `JAVA_HOME` appropriately by adding it to the `PATH`.
. Install link:{maven_install_url}[Apache Maven] {maven_min_version}.
. Install link:{quarkus_cli_url}[Quarkus CLI] corresponding to the currently supported version by {product_name}. Currently, it is {quarkus_version}.

[[proc-additional-options-for-local-environment]]
== Additional options for local environment setup

Points listed in this section provide extra possibilities when working with our guides and are considered optional.

* Install link:{graalvm_url}[GraalVM] {graalvm_min_version}. This will allow you to create link:{graalvm_native_image_url}[native image] of your {product_name} application.
* Install link:{knative_serving_install_yaml_url}[Knative Serving using YAML files] for advanced customizations or in cases where the quickstart procedure fails.
* Install link:{knative_eventing_install_yaml_url}[Knative Eventing using YAML files] for advanced customizations or in cases where the quickstart procedure fails.

== Additional resources

* xref:getting-started/production-environment.adoc[]
* xref:getting-started/create-your-first-workflow-service-with-kn-cli-and-vscode.adoc[]

include::../../pages/_common-content/report-issue.adoc[]