= Production environment

[IMPORTANT]
====
[subs="attributes+"]
{serverlessproductname} is a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs) and
might not be functionally complete. Red Hat does not recommend using them
in production. These features provide early access to upcoming product
features, enabling customers to test functionality and provide feedback during
the development process.

For more information about the support scope of Red Hat Technology Preview
features, see https://access.redhat.com/support/offerings/techpreview/.
====

In thise guide, you can find {product_name} recommendations and best-practices for production environment.

As a cluster environment, We recommend using https://docs.openshift.com/container-platform/4.15/welcome/index.html[Red Hat Openshift Container Platform].
Make sure you are using https://docs.openshift.com/serverless/1.32/about/about-knative-serving.html[Knative Serving] and https://docs.openshift.com/serverless/1.32/install/installing-knative-eventing.html featured in https://docs.openshift.com/serverless/1.32/about/about-serverless.html[Red Hat Openshift Serverless] when using {product_name} in production.

Are you using {product_name} in production? Let us know how so that we can expand our test suites!

== Additional resources

* xref:cloud/index.adoc[]

include::../../pages/_common-content/report-issue.adoc[]