= Orchestrating AsyncAPI Services
:compat-mode!:
// Metadata:
:description: Orchestration of AsyncAPI based services
:keywords: kogito, workflow, serverless, AsyncApi, quarkiverse
// links:
:async_api_spec_url: https://www.asyncapi.com/docs/reference/specification/v2.0.0
:async_quarkiverse_url: https://github.com/quarkiverse/quarkus-asyncapi
// Referenced documentation pages.
:kafka_config: xref:eventing/consume-producing-events-with-kafka.adoc
:knative_config: xref:eventing/consume-produce-events-with-knative-eventing.adoc
:event_states: xref:core/handling-events-on-workflows.adoc

This document describes how to trigger and publish events using an link:{async_api_spec_url}[AsyncAPI] specification file.
Underneath, {product_name} uses the link:{async_quarkiverse_url}[AsyncAPI Quarkiverse extension]. 
This extension automatically generates all the required link:{smallrye_messaging_url}[Smallrye] properties to make {product_name} work with the servers declared in the AsyncAPI file. Therefore, you do not need to add any property specific to your event broker to make AsyncAPI work. This is a huge advantage over regular {event_states}[event states], where whether using {kafka_config}[Kafka] or {knative_config}[Knative], you have to provide additional configuration 

[NOTE]
====
AsyncAPI Quarkiverse extension only supports `kafka` and `http` protocols at the moment. 
====


== Consuming an event

Let's assume there is an AsyncAPI specification file called `asyncAPI.yaml`, located in the classpath of your project. 

This file contains a `servers` definition which `protocol` is Kafka: 

.Example of an AsyncAPI kafka server definition
[source,yaml]
----
servers:
  development:
    url: localhost:9092
    description: Development server
    protocol: kafka
    protocolVersion: '1.0.0'
----

and a subscription channel named `wait`: 

.Example of an AsyncAPI subscribing channel definition
[source,yaml]
----
channels:
  wait:
    description: A message channel
    subscribe:
      operationId: consumeWait
      summary: Get messages
      message:
        $ref: '#/components/messages/message'
----

You can define a function in your workflow, of type `asyncapi`, that points to `consumerWait` operationId:

.Example of an AsyncAPI subscribing function definition
[source,json]
----
{
   "functions": [
      {
          "name": "consumeEvent",
          "type": "asyncapi",
          "operation": "asyncAPI.yaml#consumeWait" 
       }
   ]
}
----

[NOTE]
====
Remember that, as happens with `REST` and `RPC` types, the URI part of the `operation` property supports `http`, `https`, and `file` schemas. If no schema is present, it assumes the specification file is on the project classpath.
====

Once the function is defined, you can invoke it within an `operation` state: 

.Example of an AsyncAPI subscribing function invocation
[source,json]
----
   {
      "name": "waitForEvent",
      "type": "operation",
      "actions": [
          { 
           "functionRef": "consumeEvent"
          }
       ]      
    }
----

When your flow reach the `waitForEvent` state, it will stop until it receives a CloudEvent published over the Kafka topic `wait`. 

== Publishing an event

Let's assume there is an AsyncAPI specification file called `asyncAPI.yaml`, located in the classpath of your project. 

This file contains a `servers` definition which `protocol` is HTTP:

.Example of an AsyncAPI http server definition
[source,yaml]
----
servers:
  development:
    url: localhost:8080
    description: Development server
    protocol: http
    protocolVersion: '1.0.0'
----

and a publishing channel named `resume`: 

.Example of an AsyncAPI publishing channel definition
[source,yaml]
----
channels:
  resume:
    description: A message channel
    publish:
      operationId: sendResume
      summary: Get messages
      message:
        $ref: '#/components/messages/message'
----

You can define a function in your workflow, of type `asyncapi`, that point to `sendResume` operationId:

.Example of an AsyncAPI publishing function definition
[source,json]
----
{
   "functions": [
      {
          "name": "sendResume",
          "type": "asyncapi",
          "operation": "asyncAPI.yaml#sendResume" 
       }
   ]
}
----

Once the function is defined, you can invoke it within an `operation` state:

.Example of an AsyncAPI publishing function invocation
[source,json]
----
   {
      "name": "sendEvent",
      "type": "operation",
      "actions": [
          { 
           "functionRef": "sendResume",
           "arguments" : {
              "name" : "Javierito"
            }
          }
       ]      
    }
----

When your flow reach the `sendEvent` state, it will send an event to the endpoint `http://localhost:8080/resume`, with the payload `{"name":"Javierito"}`


include::../../pages/_common-content/report-issue.adoc[]
