= {product_name} integration test using PostgreSQL
:compat-mode!:
// Metadata:
:description: Serverless Workflow integration test with PostgreSQL
:keywords: kogito, workflow, quarkus, serverless, quarkus-cli, test, integration, postgresql, persistence
// Referenced documentation pages
:basic_integration_test_with_restassured_guide: xref:testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
:getting_started_create_first_workflow_guide: xref:getting-started/create-your-first-workflow-service.adoc
:persistence_with_postgresql_guide: xref:persistence/persistence-with-postgresql.adoc
// External pages
:quarkus_testing_guide_url: {quarkus_guides_base_url}/getting-started-testing
:quarkus_testing_guide_integration_test_url: {quarkus_testing_guide_url}#quarkus-integration-test
:quarkus_testing_guide_test_resource: {quarkus_testing_guide_url}#quarkus-test-resource
:quarkus_testing_guide_launching_containers_url: {quarkus_testing_guide_url}#launching-containers
:quarkus_dev_services_url: {quarkus_guides_base_url}/dev-services
:quarkus_database_dev_services_url: {quarkus_guides_base_url}/databases-dev-services
:awaitility_url: http://www.awaitility.org/
:postgresql_url: https://www.postgresql.org/
:postgresql_doc_url: https://www.postgresql.org/docs/current/
:failsafe_pluggin_doc: https://maven.apache.org/surefire/maven-failsafe-plugin/index.html
:failsafe_pluggin_inclusions: https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html
:kogito_sw_callback_example_url: {kogito_sw_examples_url}/serverless-workflow-callback-quarkus

This document describes how you can test your integrated workflow application using PostgreSQL persistence.

The example described in this document is based on the link:{kogito_sw_callback_example_url}[`serverless-workflow-callback-quarkus`] example application.

[[con-integration-test-overview]]
== Overview

This document describes the process of launching and testing the artifact that is produced by the Quarkus builds, and verifying the interaction of the artifact with a PostgreSQL database instance. To perform this scenario and verify the service behavior, the following Quarkus annotations and tools are used:

* `@QuarkusIntegrationTest`: This annotation is used to launch and test the artifact produced by the Serverless Workflow Quarkus build. For more information, see link:{quarkus_testing_guide_integration_test_url}[Testing Quarkus application - Using `@QuarkusIntegrationTest`] in Quarkus documentation.
* Quarkus Dev Services: This facilitates writing integration tests that need launching services to support the workflow application. For more information, see link:{quarkus_testing_guide_launching_containers_url}[Testing Quarkus application - launching containers] in Quarkus documentation.
+
`@QuarkusIntegrationTest` works immediately with the additional containers that are launched using link:{quarkus_dev_services_url}[Quarkus Dev Services].

[[proc-test-sw-application-postgresql]]
== Testing a workflow application using PostgreSQL persistence

You can test your workflow application using PostgreSQL persistence.

.Prerequisites
include::../../pages/_common-content/getting-started-requirement.adoc[]
* Workflow application persistence is enabled using PostgreSQL.
+
For more information, see {persistence_with_postgresql_guide}[Running workflow service using PostgreSQL].

* Docker is installed.

.Procedure
. Add the required test dependencies to the `pom.xml` file of your workflow application:
+
--
.Dependencies required for HTTP-based testing in JVM mode
[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-junit5</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <scope>test</scope>
</dependency>
----

.Add `awaitility` dependency in `pom.xml`
[source,xml]
----
<dependency>
  <groupId>org.awaitility</groupId>
  <artifactId>awaitility</artifactId>
  <scope>test</scope>
</dependency>
----

The `awaitility` dependency allows the test to express the time expectations of an asynchronous system. For more information, see link:{awaitility_url}[Awaitility] website.
--

. Check the dependencies of PostgreSQL resources.
+
--
The link:{quarkus_database_dev_services_url}[Quarkus Dev Services for Databases] is enabled when a reactive or JDBC data source extension is present in the workflow application.

Ensure that the `pom.xml` file of your workflow application contains the required dependency for PostgreSQL resources.

.JDBC persistence add-on dependency
[source,xml]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-jdbc</artifactId>
</dependency>
----

.Quarkus JDBC PostgreSQL dependency
[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
----

.Quarkus Agroal data source dependency
[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-agroal</artifactId>
</dependency>
----
--

. To run the integration tests, add Apache Maven Failsafe plug-in in the `pom.xml` file of your workflow application.
+
--
.`maven-failsafe-plugin` in `pom.xml` plug-in section
[source,xml]
----
<plugin>
  <artifactId>maven-failsafe-plugin</artifactId>
  <version>${version.failsafe.plugin}</version>
  <configuration>
    <systemPropertyVariables>
      <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
      <maven.home>${maven.home}</maven.home>
    </systemPropertyVariables>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>integration-test</goal>
        <goal>verify</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

For more information about `maven-failsafe-plugin`, see link:{failsafe_pluggin_doc}[Maven Failsafe Plugin] documentation.

--

. Enable Quarkus Database Dev Services.
+
--
The additional containers contain a full set of default configurations, including PostgreSQL Docker image name, default user, and default password. The required configuration to link the workflow application with the Quarkus Dev PostgreSQL container is automatically added to the integration test. Quarkus provides the properties such as `quarkus.datasource.reactive.url`, `quarkus.datasource.jdbc.url`, `quarkus.datasource.username`, or `quarkus.datasource.password`, when you start the container. 

For more information, see link:{quarkus_database_dev_services_url}[Quarkus Dev Services for Databases] in Quarkus documentation.
--

. Create a test class and add the test annotations in the test class as shown in the following example:
+
--
.Example integration test annotations in a test class
[source,java]
----
@QuarkusIntegrationTest <1>
class CallbackRestIT { <2>
    static {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();<3>
    }

    @Test
    void testCallbackRest() {
        String id = given() <3>
                .contentType(ContentType.JSON)
                .accept(ContentType.JSON)
                .post("/callback")
                .then()
                .statusCode(201)
                .extract()
                .path("id");

        await() <4>
                .atLeast(1, SECONDS)
                .atMost(30, SECONDS)
                .with().pollInterval(1, SECONDS)
                .untilAsserted(() -> given()
                        .contentType(ContentType.JSON)
                        .accept(ContentType.JSON)
                        .get("/callback/{id}", id)
                        .then()
                        .statusCode(404));
    }
}
----
<1> Allows launching and testing the artifact that is produced by the Quarkus build. Also, supports testing of a JAR file, a native image, or a container image.
<2> Test name ends with 'IT' to identify which test needs to be executed as an integration test.
<3> Testing application interactions using REST Assured.
<4> `await()` allows the test to retry the validations until the verifications are declared or until the specified time expectation is expired.

Once you specify the required resources and annotations, you can start testing the different interactions with the workflow application as described in {basic_integration_test_with_restassured_guide}[Testing your workflow application using REST Assured] document.
--

. To run the tests, execute the following command:
+
--
.Run the tests
[source,shell]
----
mvn clean verify
----
--

== Additional resources

* {getting_started_create_first_workflow_guide}[Creating your first workflow service]
* {persistence_with_postgresql_guide}[Running a workflow service using PostgreSQL]
* {basic_integration_test_with_restassured_guide}[Testing your workflow application using REST Assured]
* link:{quarkus_testing_guide_url}[Testing a Quarkus application]

include::../../pages/_common-content/report-issue.adoc[]
