// Module included in the following assemblies
//
// functions/dev_guide/internal_registry/internal-registry.adoc

A common use case for building and deploying Functions is to use an external container image registry, such as Quay. However, you can instead use an OpenShift Container Platform internal registry, if it has been exposed:

. link:https://docs.openshift.com/container-platform/latest/registry/securing-exposing-registry.html[Expose an internal OpenShift Container Registry.]

. Run the `kn func build` or `kn func deploy` function as you normally would, but specify the exposed internal registry for the `-r` parameter:
+
[source]
----
$ kn func build -i my-image -r image-registry.openshift-image-registry.svc???
----
+
[source]
----
$ kn func deploy -n my-namespace -i my-image -r image-registry.openshift-image-registry.svc???
----

. Optionally, to verify that the function has been deployed, list all deployed functions in the namespace:
+
[source]
----
$ kn service list -n my-namespace
----

. You can invoke the function the same way as if you used an external registry. See documentation on the individual runtimes for instructions.
