// Module included in the following assemblies
//
// functions/quickstart-functions.adoc
// nav.adoc

// [id="build-function-kn_{context}"]
= Building a function

You can build a function project by using the `kn func build` command.

The build command reads the `func.yaml` file in the directory for your function to determine the image name and registry.

.Example `func.yaml`
[source,yaml]
----
name: fn.example.io
namespace: default
runtime: node
image: <image_from_registry>
imageDigest: ""
trigger: http
builder: default
builderMap:
  default: quay.io/boson/faas-nodejs-builder
envVars: {}
----

If both of these values are unset, you will be prompted to provide a registry.
An image name is then be derived from the registry.

The value(s) provided for image and registry are persisted to the `func.yaml` file, so that subsequent invocations do not require the user to specify these again.

.Procedure
// have to initialize a function first, then nav to or provide the path to it
* Build a function:
+
[source,terminal]
----
$ kn func build [-i <image> -r <registry> -p <path>]
----
