= Running a Quarkus Workflow Application using PostgreSQL
:compat-mode!:
// Metadata:
:description: Running Quarkus Workflow Application using PostgresSQL
:keywords: kogito, workflow, quarkus, serverless, quarkus-cli, persistence, postgresql
// Referenced documentation pages.
:getting_started_create_first_workflow_guide: xref:getting-started/create-your-first-workflow-service.adoc
:persistence_with_postgresql_guide: xref:persistence/persistence-with-postgresql.adoc
// External pages
:quarkus_datasource_guide: https://quarkus.io/guides/datasource
:quarkus_datasource_devservices_guide: https://quarkus.io/guides/databases-dev-services
:kogito_sw_callback_example: {kogito_sw_examples_url}/serverless-workflow-callback-quarkus
:postgresql_url: https://www.postgresql.org/
:postgresql_doc_url: https://www.postgresql.org/docs/current/
:flyway_url: https://flywaydb.org/

The {product_name} PostgreSQL persistence is provided by the `kogito-addons-quarkus-persistence-jdbc` add-on, which is based on the Java Database Connectivity (JDBC).
Additionally, it uses the Quarkus JDBC for PostgreSQL and Argoal Datasource extensions to connect with the database. And thus, it automatically inherits all the features of these extensions.
For more information about Quarkus and JDBC, see link:{quarkus_datasource_guide}[Quarkus Datasources].

To see how to configure the PostgreSQL persistence, we recommend that follow the `serverless-workflow-callback-quarkus` example application in the link:{kogito_examples_repository_url}[GitHub repository], or apply the <<#configuration_procedure, configuration procedure>> directly in your project.

.Getting the serverless-workflow-callback-quarkus application
. In a command terminal, clone the `kogito-examples` repository, navigate to the cloned directory, and follow link:{kogito_sw_examples_url}/serverless-workflow-callback-quarkus/README.md[these steps]:
[source, bash]
----
git clone https://github.com/apache/incubator-kie-kogito-examples.git

cd kogito-examples/serverless-workflow-examples/serverless-workflow-callback-quarkus
----

.Prerequisites
include::../../../../pages/_common-content/getting-started-requirement-quarkus.adoc[]
* Docker is installed.
* link:{postgresql_url}[PostgreSQL] is installed. For information about PostgreSQL installation and configuration, see link:{postgresql_doc_url}[PostgreSQL documentation].

[NOTE]
====
This document relies on running PostgreSQL as a Docker service, however, if you are not following the `serverless-workflow-callback-quarkus` example you can use your own PostgreSQL installation.
====

[#configuration_procedure]
.Procedure
. Add required dependencies to the `pom.xml` file of your project to use the persistence add-on:
+
--
.JDBC persistence add-on
[source,xml]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-jdbc</artifactId>
</dependency>
----

.Quarkus JDBC PostgreSQL
[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
----

.Quarkus Agroal data source
[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-agroal</artifactId>
</dependency>
----
--

. Add the following properties to the `application.properties` file of your project:
+
--
.Persistence property
[source, properties]
----
kogito.persistence.type=jdbc
----

.Quarkus properties
[source, properties]
----
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
----
--

. Create PostgreSQL database schema.
+
[#create-database-schema]
--
The persistence add-on uses link:{flyway_url}[Flyway] to create the database schema. To enable the database schema creation during the runtime startup, you must set the following properties in the `application.properties` file.

[source,properties]
----
quarkus.flyway.migrate-at-start=true
quarkus.datasource.db-kind=postgresql
----

You can find more details regarding the PostgreSQL database schema migration in the xref:use-cases/advanced-developer-use-cases/persistence/postgresql-flyway-migration.adoc[Flyway migration guide].
--

. Optional: To handle the concurrent requests to shared workflow instances, enable the persistence-enabled optimistic locking for concurrency control using the version field in the database. 
+
--
Add `kogito.persistence.optimistic.lock=true` property in the `application.properties` file of your project to enable the optimistic locking.
--

. Change the version in the workflow file.
+
--
.Example workflow file
[source,json]
----
{
  "id": "applicantworkflow",
  "name": "Applicant Workflow",
  "version": "1.0"
}
----
The versioning strategy is used to allow different workflow applications to run different versions of a process at the same time. The different versions of a process share the same database. This is useful when you migrate a process from one version to another. When allowing workflow instances to finish executing, a new version can be deployed using a new workflow application setup. 

By default, the engine considers the `version` specified in the workflow file as the current version of the asset. Therefore, you need to manually change the `version` in the workflow file, making the engine consider the specified version as a new version.

As an alternative, you can set the `kogito.workflow.version-strategy=project` property in the `application.properties` file of your project. This enables the engine to consider the Maven or Gradle project version as the version of all workflows in the project. For instance, when you release a new version of your Maven project, the version in the workflow file is automatically updated. 
--

[[ref-postgresql-persistence-configuration]]
== Persistence configuration quick reference

The following table serves as a quick reference of commonly used persistence configuration properties supported in {product_name}. You can define these properties in the `application.properties` file of your project.

.Persistence properties
[cols="40%,30%,30%", options="header"]
|===
|Configuration property|Type|Default value

|`kogito.persistence.type`
|string
|

|`kogito.persistence.query.timeout.millis`
|long
|`10000`

|`kogito.persistence.optimistic.lock`
|boolean
|`false`

|`kogito.workflow.version-strategy`
|string
|`workflow`

|===


[[postgresql-persistence-additional-resources]]
== Additional resources

* xref:use-cases/advanced-developer-use-cases/persistence/postgresql-advanced-concepts.adoc[Postgresql Advanced Concepts]
* xref:use-cases/advanced-developer-use-cases/persistence/postgresql-flyway-migration.adoc[PostgreSQL Database Migration]
* xref:use-cases/advanced-developer-use-cases/persistence/integration-tests-with-postgresql.adoc[{product_name} integration test using PostgreSQL]

include::../../../../pages/_common-content/report-issue.adoc[]