= About OpenShift Serverless Logic

[IMPORTANT]
====
OpenShift Serverless Logic is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview
features, see https://access.redhat.com/support/offerings/techpreview/.
====

_OpenShift Serverless Logic_ enables developers or architects to define declarative workflow models that orchestrate event-driven, serverless applications. Serverless Logic implements the link:https://github.com/serverlessworkflow/specification[CNCF Serverless Workflow specification], allowing developers and architects to define logical steps of execution declaratively (no code) for cloud-native services. The specification is hosted by the link:https://www.cncf.io/[Cloud Native Computing Foundation (CNCF)] and is currently a link:https://www.cncf.io/projects/serverless-workflow/[CNCF Sandbox project].

OpenShift Serverless Logic is also designed to write workflows in formats (JSON or YAML) that might be better suited for developing and deploying serverless applications in cloud or container environments.

For Serverless Logic implementation, link:https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes Operator] can be used to deploy the workflow models using link:https://knative.dev/docs/[Knative]. link:https://knative.dev/docs/eventing/[Knative Eventing] plays an important role and provides the essential infrastructure for event-driven architectures.
