// Module included in the following assemblies
// /functions/user_guide/develop-nodejs.adoc

// [id="invoking-nodejs_{context}"]
// = Invoking Node.js functions

Functions can be invoked with a simple HTTP request. When an incoming request is received, functions are invoked with a `context` object as the first parameter.

If the incoming request is a CloudEvent, any data associated with the CloudEvent is extracted from the event and provided as a second parameter. For example, if a CloudEvent is received which contains a JSON string similar to the following in its data property:

[source,json]
----
{
  "customerId": "0123456",
  "productId": "6543210"
}
----

When invoked, the second parameter to the function, after the `context` object, will be a JavaScript object that has `customerId` and `productId` properties.

.Example signature
[source,javascript]
----
function processPurchase(context, data)
----

The `data` parameter in this example is a JavaScript object that contains the `customerId` and `productId` properties.
