// Module included in the following assemblies
// /functions/dev_guide/develop-nodejs.adoc

// [id="invoking-nodejs"]
// = Invoking Node.js functions

Node.js functions can be invoked with a simple HTTP request. When an incoming request is received, functions are invoked with a `context` object as the first parameter.

== Context objects

Functions are invoked by providing a `context` object as the first parameter.

.Example context object
[source,js]
----
function handle(context, event)
----

This object provides access to the incoming HTTP request information, including the HTTP request method, any query strings or headers sent with the request, the HTTP version, and the request body.

Incoming requests that contain a CloudEvent provide the incoming instance of the CloudEvent as the second parameter to the function.

=== Context object methods

The `context` object has a single method, `cloudEventResponse()` that accepts a data value and returns a CloudEvent.

In a Knative system, if a function deployed as a service is invoked by an event broker sending a CloudEvent, the broker will examine the response. If the response is a CloudEvent, this event will then be handled by the broker.

.Example
[source,js]
----
// Expects to receive a CloudEvent with customer data
function handle(context, event) {
  // process the customer
  const processed = processCustomer(event.data);
  return context.cloudEventResponse(event.data);
}
----

== CloudEvent data

If the incoming request is a CloudEvent, any data associated with the CloudEvent is found in the `event.data` attribute. For example, if a CloudEvent is received which contains a JSON string similar to the following in its data property:

[source,json]
----
{
  "customerId": "0123456",
  "productId": "6543210"
}
----

When invoked, the second parameter to the function, after the `context` object, will be a CloudEvent that has `customerId` and `productId` properties in the `data`.

.Example signature
[source,javascript]
----
function handle(context, event) {
  console.log(event.data.customerId);
}
----

The `data` attrribute of the CloudEvent is a JavaScript object that contains the `customerId` and `productId` properties.
