// Module included in the following assemblies
// /functions/dev_guide/develop-nodejs.adoc

// [id="invoking-nodejs"]
// = Invoking Node.js functions

Node.js functions can be invoked with a simple HTTP request. When an incoming request is received, functions are invoked with a `context` object as the first parameter.

== Context objects

Functions are invoked by providing a `context` object as the first parameter.

.Example context object
[source,js]
----
function processPurchase(context, data)
----

This object provides access to the incoming HTTP request information, including the HTTP request method, any query strings or headers sent with the request, the HTTP version, and the request body.

Incoming requests that contain a CloudEvent attach the incoming instance of the CloudEvent to the context object, so that it can be accessed using `context.cloudevent`.

=== Context object methods

The `context` object has a single method, `cloudEventResponse()` that accepts a data value and returns a CloudEvent.

In a Knative system, if a function deployed as a service is invoked by an event broker sending a CloudEvent, the broker will examine the response. If the response is a CloudEvent, this event will then be handled by the broker.

.Example
[source,js]
----
// Expects to receive a CloudEvent with customer data
function processCustomer(context, customer) {
  // process the customer
  const processed = processCustomer(customer);
  return context.cloudEventResponse(customer);
}
----

== CloudEvent data

If the incoming request is a CloudEvent, any data associated with the CloudEvent is extracted from the event and provided as a second parameter. For example, if a CloudEvent is received which contains a JSON string similar to the following in its data property:

[source,json]
----
{
  "customerId": "0123456",
  "productId": "6543210"
}
----

When invoked, the second parameter to the function, after the `context` object, will be a JavaScript object that has `customerId` and `productId` properties.

.Example signature
[source,javascript]
----
function processPurchase(context, data)
----

The `data` parameter in this example is a JavaScript object that contains the `customerId` and `productId` properties.
