// Module included in the following assemblies
//
// functions/user_guide/develop-nodejs.adoc

// [id="return-values-nodejs_{context}"]
= Return values

Functions can return any valid JavaScript type or can have no return value. When a function has no return value specified, and no failure is indicated, the caller will receive a `204 No Content` response.

Functions may also return a CloudEvent, or a `Message` object in order to push events into the Knative Eventing system. In this case, the developer is not required to understand or implement the CloudEvent messaging specification. Headers and other relevant information from the returned values are extracted and sent with the response.

.Example
[source,javascript]
----
function processCustomer(context, customer) {
  // process customer and return a new CloudEvent
  return new CloudEvent({
    source: 'customer.processor',
    type: 'customer.processed'
  })
}
----

== Returning headers

You can set a response header by adding a `headers` property to the `return` object. These headers will be extracted and sent with the response to the caller.

.Example response header
[source,javascript]
----
function processCustomer(context, customer) {
  // process customer and return custom headers
  // the response will be '204 No content'
  return { headers: { customerid: customer.id } };
}
----

== Returning status codes

You can set a status code that is returned to the caller by adding a `statusCode` property to the `return` object.

.Example status code
[source,javascript]
----
function processCustomer(context, customer) {
  // process customer
  if (customer.restricted) {
    return { statusCode: 451 }
  }
}
----

// Can we add a statusCode doc that gives all the codes?
Status codes can also be set for errors that are defined in the function.

.Example error status code
[source,javascript]
----
function processCustomer(context, customer) {
  // process customer
  if (customer.restricted) {
    const err = new Error(‘Unavailable for legal reasons’);
    err.statusCode = 451;
    throw err;
  }
}
----
